/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as DiagnosticosRouteImport } from './routes/diagnosticos'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as KardexRouteImport } from './routes/kardex'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManoObraRouteImport } from './routes/mano-obra'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as OrdenesRouteImport } from './routes/ordenes'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as RecepcionRouteImport } from './routes/recepcion'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RepuestosOrdenRouteImport } from './routes/repuestos-orden'
import { Route as RespaldosRouteImport } from './routes/respaldos'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VehiculosRouteImport } from './routes/vehiculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticosRoute = DiagnosticosRouteImport.update({
  id: '/diagnosticos',
  path: '/diagnosticos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const KardexRoute = KardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManoObraRoute = ManoObraRouteImport.update({
  id: '/mano-obra',
  path: '/mano-obra',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesRoute = OrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionRoute = RecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepuestosOrdenRoute = RepuestosOrdenRouteImport.update({
  id: '/repuestos-orden',
  path: '/repuestos-orden',
  getParentRoute: () => rootRouteImport,
} as any)
const RespaldosRoute = RespaldosRouteImport.update({
  id: '/respaldos',
  path: '/respaldos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/entregas': typeof EntregasRoute
  '/facturacion': typeof FacturacionRoute
  '/garantias': typeof GarantiasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kardex': typeof KardexRoute
  '/login': typeof LoginRoute
  '/mano-obra': typeof ManoObraRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/ordenes': typeof OrdenesRoute
  '/proveedores': typeof ProveedoresRoute
  '/recepcion': typeof RecepcionRoute
  '/reportes': typeof ReportesRoute
  '/repuestos-orden': typeof RepuestosOrdenRoute
  '/respaldos': typeof RespaldosRoute
  '/servicios': typeof ServiciosRoute
  '/usuarios': typeof UsuariosRoute
  '/vehiculos': typeof VehiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/entregas': typeof EntregasRoute
  '/facturacion': typeof FacturacionRoute
  '/garantias': typeof GarantiasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kardex': typeof KardexRoute
  '/login': typeof LoginRoute
  '/mano-obra': typeof ManoObraRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/ordenes': typeof OrdenesRoute
  '/proveedores': typeof ProveedoresRoute
  '/recepcion': typeof RecepcionRoute
  '/reportes': typeof ReportesRoute
  '/repuestos-orden': typeof RepuestosOrdenRoute
  '/respaldos': typeof RespaldosRoute
  '/servicios': typeof ServiciosRoute
  '/usuarios': typeof UsuariosRoute
  '/vehiculos': typeof VehiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/diagnosticos': typeof DiagnosticosRoute
  '/entregas': typeof EntregasRoute
  '/facturacion': typeof FacturacionRoute
  '/garantias': typeof GarantiasRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/kardex': typeof KardexRoute
  '/login': typeof LoginRoute
  '/mano-obra': typeof ManoObraRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/ordenes': typeof OrdenesRoute
  '/proveedores': typeof ProveedoresRoute
  '/recepcion': typeof RecepcionRoute
  '/reportes': typeof ReportesRoute
  '/repuestos-orden': typeof RepuestosOrdenRoute
  '/respaldos': typeof RespaldosRoute
  '/servicios': typeof ServiciosRoute
  '/usuarios': typeof UsuariosRoute
  '/vehiculos': typeof VehiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/cotizaciones'
    | '/diagnosticos'
    | '/entregas'
    | '/facturacion'
    | '/garantias'
    | '/historial'
    | '/inventario'
    | '/kardex'
    | '/login'
    | '/mano-obra'
    | '/mantenimiento'
    | '/notificaciones'
    | '/ordenes'
    | '/proveedores'
    | '/recepcion'
    | '/reportes'
    | '/repuestos-orden'
    | '/respaldos'
    | '/servicios'
    | '/usuarios'
    | '/vehiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/cotizaciones'
    | '/diagnosticos'
    | '/entregas'
    | '/facturacion'
    | '/garantias'
    | '/historial'
    | '/inventario'
    | '/kardex'
    | '/login'
    | '/mano-obra'
    | '/mantenimiento'
    | '/notificaciones'
    | '/ordenes'
    | '/proveedores'
    | '/recepcion'
    | '/reportes'
    | '/repuestos-orden'
    | '/respaldos'
    | '/servicios'
    | '/usuarios'
    | '/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/cotizaciones'
    | '/diagnosticos'
    | '/entregas'
    | '/facturacion'
    | '/garantias'
    | '/historial'
    | '/inventario'
    | '/kardex'
    | '/login'
    | '/mano-obra'
    | '/mantenimiento'
    | '/notificaciones'
    | '/ordenes'
    | '/proveedores'
    | '/recepcion'
    | '/reportes'
    | '/repuestos-orden'
    | '/respaldos'
    | '/servicios'
    | '/usuarios'
    | '/vehiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AyudaRoute: typeof AyudaRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CotizacionesRoute: typeof CotizacionesRoute
  DiagnosticosRoute: typeof DiagnosticosRoute
  EntregasRoute: typeof EntregasRoute
  FacturacionRoute: typeof FacturacionRoute
  GarantiasRoute: typeof GarantiasRoute
  HistorialRoute: typeof HistorialRoute
  InventarioRoute: typeof InventarioRoute
  KardexRoute: typeof KardexRoute
  LoginRoute: typeof LoginRoute
  ManoObraRoute: typeof ManoObraRoute
  MantenimientoRoute: typeof MantenimientoRoute
  NotificacionesRoute: typeof NotificacionesRoute
  OrdenesRoute: typeof OrdenesRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecepcionRoute: typeof RecepcionRoute
  ReportesRoute: typeof ReportesRoute
  RepuestosOrdenRoute: typeof RepuestosOrdenRoute
  RespaldosRoute: typeof RespaldosRoute
  ServiciosRoute: typeof ServiciosRoute
  UsuariosRoute: typeof UsuariosRoute
  VehiculosRoute: typeof VehiculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticos': {
      id: '/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof DiagnosticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kardex': {
      id: '/kardex'
      path: '/kardex'
      fullPath: '/kardex'
      preLoaderRoute: typeof KardexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mano-obra': {
      id: '/mano-obra'
      path: '/mano-obra'
      fullPath: '/mano-obra'
      preLoaderRoute: typeof ManoObraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes': {
      id: '/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof OrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion': {
      id: '/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof RecepcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repuestos-orden': {
      id: '/repuestos-orden'
      path: '/repuestos-orden'
      fullPath: '/repuestos-orden'
      preLoaderRoute: typeof RepuestosOrdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respaldos': {
      id: '/respaldos'
      path: '/respaldos'
      fullPath: '/respaldos'
      preLoaderRoute: typeof RespaldosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  AyudaRoute: AyudaRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CotizacionesRoute: CotizacionesRoute,
  DiagnosticosRoute: DiagnosticosRoute,
  EntregasRoute: EntregasRoute,
  FacturacionRoute: FacturacionRoute,
  GarantiasRoute: GarantiasRoute,
  HistorialRoute: HistorialRoute,
  InventarioRoute: InventarioRoute,
  KardexRoute: KardexRoute,
  LoginRoute: LoginRoute,
  ManoObraRoute: ManoObraRoute,
  MantenimientoRoute: MantenimientoRoute,
  NotificacionesRoute: NotificacionesRoute,
  OrdenesRoute: OrdenesRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecepcionRoute: RecepcionRoute,
  ReportesRoute: ReportesRoute,
  RepuestosOrdenRoute: RepuestosOrdenRoute,
  RespaldosRoute: RespaldosRoute,
  ServiciosRoute: ServiciosRoute,
  UsuariosRoute: UsuariosRoute,
  VehiculosRoute: VehiculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
