export type FieldType = "text" | "number" | "textarea" | "select" | "combo" | "date";

/** Fuentes de opciones calculadas en tiempo real (ver ModulePage). */
export type DynamicOptionsSource = "mecanicos" | "ordenes";

export interface ComboOption {
  /** Valor que se guarda (p. ej. el código de la orden). */
  value: string;
  /** Texto que se muestra en la lista. */
  label: string;
  /** Palabras extra por las que también se puede buscar (cliente, placa, etc.). */
  keywords?: string;
}

export interface FieldDef {
  name: string;
  label: string;
  type?: FieldType;
  /** Opciones de un campo "select". */
  options?: string[];
  /** Opciones de un campo "combo" (select con buscador). */
  comboOptions?: ComboOption[];
  /** Si se define, las opciones de un campo "select"/"combo" se calculan en vivo en vez de usar `options`/`comboOptions`. */
  dynamicOptions?: DynamicOptionsSource;
  required?: boolean;
  span?: 1 | 2;
}

export interface ColumnDef {
  name: string;
  label: string;
  kind?: "text" | "money" | "badge" | "number";
}

export interface EntityRow {
  id: string;
  [key: string]: string | number;
}

export interface EntityDef {
  key: string;
  title: string;
  subtitle: string;
  rf: string;
  singular: string;
  fields: FieldDef[];
  columns: ColumnDef[];
  seed: EntityRow[];
  /** roles allowed to write */
  write?: Array<"ADMIN" | "MECANICO">;
}

const ESTADOS = ["Activo", "Inactivo"];

export const ENTITIES: Record<string, EntityDef> = {
  usuarios: {
    key: "usuarios",
    title: "Usuarios",
    subtitle: "Gestión de usuarios internos, roles y estado de la cuenta.",
    rf: "RF-003 · RF-004",
    singular: "usuario",
    write: ["ADMIN"],
    fields: [
      { name: "documento", label: "Documento", required: true },
      { name: "nombre", label: "Nombre", required: true },
      { name: "apellidos", label: "Apellidos", required: true },
      { name: "usuario", label: "Usuario", required: true },
      { name: "correo", label: "Correo" },
      { name: "telefono", label: "Teléfono" },
      { name: "rol", label: "Rol", type: "select", options: ["Administrador", "Mecánico"] },
      { name: "estado", label: "Estado", type: "select", options: [...ESTADOS, "Bloqueado"] },
    ],
    columns: [
      { name: "documento", label: "Documento" },
      { name: "nombre", label: "Nombre" },
      { name: "apellidos", label: "Apellidos" },
      { name: "usuario", label: "Usuario" },
      { name: "rol", label: "Rol", kind: "badge" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "u1",
        documento: "1094921233",
        nombre: "Carlos",
        apellidos: "Restrepo Ávila",
        usuario: "crestrepo",
        correo: "admin@matergarage.co",
        telefono: "3104458821",
        rol: "Administrador",
        estado: "Activo",
      },
      {
        id: "u2",
        documento: "1032445119",
        nombre: "Andrés",
        apellidos: "Molina Cruz",
        usuario: "amolina",
        correo: "amolina@matergarage.co",
        telefono: "3115562210",
        rol: "Mecánico",
        estado: "Activo",
      },
      {
        id: "u3",
        documento: "80112233",
        nombre: "Julián",
        apellidos: "Ospina Vera",
        usuario: "jospina",
        correo: "jospina@matergarage.co",
        telefono: "3009987744",
        rol: "Mecánico",
        estado: "Bloqueado",
      },
    ],
  },

  clientes: {
    key: "clientes",
    title: "Clientes",
    subtitle: "Registro, actualización y búsqueda en tiempo real de clientes.",
    rf: "RF-005 a RF-009",
    singular: "cliente",
    write: ["ADMIN"],
    fields: [
      { name: "tipoDocumento", label: "Tipo documento", type: "select", options: ["CC", "CE", "NIT", "PA"] },
      { name: "documento", label: "Documento", required: true },
      { name: "nombre", label: "Nombre", required: true },
      { name: "apellidos", label: "Apellidos" },
      { name: "telefono", label: "Teléfono principal", required: true },
      { name: "telefono2", label: "Teléfono secundario" },
      { name: "correo", label: "Correo" },
      { name: "direccion", label: "Dirección" },
      { name: "ciudad", label: "Ciudad" },
      { name: "estado", label: "Estado", type: "select", options: ESTADOS },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "documento", label: "Documento" },
      { name: "nombre", label: "Nombre" },
      { name: "apellidos", label: "Apellidos" },
      { name: "telefono", label: "Teléfono" },
      { name: "ciudad", label: "Ciudad" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "c1",
        tipoDocumento: "CC",
        documento: "1017556421",
        nombre: "María Fernanda",
        apellidos: "Gómez Ruiz",
        telefono: "3126647781",
        telefono2: "",
        correo: "mf.gomez@correo.com",
        direccion: "Cra 45 #12-34",
        ciudad: "Medellín",
        estado: "Activo",
        observaciones: "Cliente frecuente, flota de 2 vehículos.",
      },
      {
        id: "c2",
        tipoDocumento: "NIT",
        documento: "900455112-3",
        nombre: "Transportes Andinos",
        apellidos: "S.A.S.",
        telefono: "6045551020",
        telefono2: "3155540011",
        correo: "compras@transandinos.co",
        direccion: "Autopista Sur km 4",
        ciudad: "Itagüí",
        estado: "Activo",
        observaciones: "Facturación a 30 días.",
      },
      {
        id: "c3",
        tipoDocumento: "CC",
        documento: "71554332",
        nombre: "Jorge Iván",
        apellidos: "Cardona",
        telefono: "3004458812",
        telefono2: "",
        correo: "jicardona@correo.com",
        direccion: "Calle 10 #8-20",
        ciudad: "Envigado",
        estado: "Inactivo",
        observaciones: "",
      },
    ],
  },

  vehiculos: {
    key: "vehiculos",
    title: "Vehículos",
    subtitle: "Ficha técnica del vehículo asociada a un único cliente.",
    rf: "RF-010 a RF-014",
    singular: "vehículo",
    write: ["ADMIN"],
    fields: [
      { name: "placa", label: "Placa", required: true },
      { name: "cliente", label: "Cliente", required: true },
      { name: "marca", label: "Marca" },
      { name: "linea", label: "Línea" },
      { name: "modelo", label: "Modelo" },
      { name: "anio", label: "Año", type: "number" },
      { name: "color", label: "Color" },
      { name: "vin", label: "VIN" },
      { name: "motor", label: "Número de motor" },
      { name: "chasis", label: "Número de chasis" },
      { name: "cilindraje", label: "Cilindraje" },
      { name: "combustible", label: "Combustible", type: "select", options: ["Gasolina", "Diésel", "Gas", "Híbrido", "Eléctrico"] },
      { name: "transmision", label: "Transmisión", type: "select", options: ["Manual", "Automática", "CVT"] },
      { name: "kilometraje", label: "Kilometraje", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: ESTADOS },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "placa", label: "Placa" },
      { name: "cliente", label: "Cliente" },
      { name: "marca", label: "Marca" },
      { name: "linea", label: "Línea" },
      { name: "anio", label: "Año" },
      { name: "kilometraje", label: "Kilometraje", kind: "number" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "v1",
        placa: "KIA412",
        cliente: "María Fernanda Gómez",
        marca: "Mazda",
        linea: "CX-30",
        modelo: "Touring",
        anio: 2021,
        color: "Gris titanio",
        vin: "JM3KFBCM1M0334512",
        motor: "PE20-441233",
        chasis: "CH-99231",
        cilindraje: "2000cc",
        combustible: "Gasolina",
        transmision: "Automática",
        kilometraje: 48250,
        estado: "Activo",
        observaciones: "",
      },
      {
        id: "v2",
        placa: "TWQ889",
        cliente: "Transportes Andinos S.A.S.",
        marca: "Chevrolet",
        linea: "NPR",
        modelo: "Reward",
        anio: 2019,
        color: "Blanco",
        vin: "9GDNPR75XKB012884",
        motor: "4JJ1-882110",
        chasis: "CH-44120",
        cilindraje: "3000cc",
        combustible: "Diésel",
        transmision: "Manual",
        kilometraje: 214300,
        estado: "Activo",
        observaciones: "Uso intensivo de carga.",
      },
      {
        id: "v3",
        placa: "HRT205",
        cliente: "Jorge Iván Cardona",
        marca: "Renault",
        linea: "Duster",
        modelo: "Intens",
        anio: 2018,
        color: "Rojo fuego",
        vin: "93YHSR2H5JJ221904",
        motor: "H4M-119822",
        chasis: "CH-11223",
        cilindraje: "1600cc",
        combustible: "Gasolina",
        transmision: "Manual",
        kilometraje: 96700,
        estado: "Activo",
        observaciones: "",
      },
    ],
  },

  recepcion: {
    key: "recepcion",
    title: "Recepción de vehículos",
    subtitle: "Orden de ingreso con consecutivo automático, checklist y registro fotográfico.",
    rf: "RF-015 a RF-017",
    singular: "ingreso",
    write: ["ADMIN"],
    fields: [
      { name: "consecutivo", label: "Consecutivo" },
      { name: "placa", label: "Placa", required: true },
      { name: "cliente", label: "Cliente", required: true },
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "hora", label: "Hora" },
      { name: "kilometraje", label: "Kilometraje", type: "number" },
      { name: "combustibleNivel", label: "Nivel combustible", type: "select", options: ["Reserva", "1/4", "1/2", "3/4", "Lleno"] },
      { name: "motivo", label: "Motivo de ingreso", type: "textarea", span: 2 },
      { name: "estado", label: "Estado", type: "select", options: ["Abierto", "Cerrado"] },
    ],
    columns: [
      { name: "consecutivo", label: "Ingreso" },
      { name: "placa", label: "Placa" },
      { name: "cliente", label: "Cliente" },
      { name: "fecha", label: "Fecha" },
      { name: "kilometraje", label: "Km", kind: "number" },
      { name: "combustibleNivel", label: "Combustible" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "r1",
        consecutivo: "ING-2026-0148",
        placa: "KIA412",
        cliente: "María Fernanda Gómez",
        fecha: "2026-08-06",
        hora: "08:15",
        kilometraje: 48250,
        combustibleNivel: "1/2",
        motivo: "Ruido en suspensión delantera y mantenimiento de 50.000 km.",
        estado: "Abierto",
      },
      {
        id: "r2",
        consecutivo: "ING-2026-0147",
        placa: "TWQ889",
        cliente: "Transportes Andinos S.A.S.",
        fecha: "2026-08-05",
        hora: "07:40",
        kilometraje: 214300,
        combustibleNivel: "3/4",
        motivo: "Revisión de frenos y cambio de aceite.",
        estado: "Cerrado",
      },
    ],
  },

  diagnosticos: {
    key: "diagnosticos",
    title: "Diagnósticos",
    subtitle: "Falla reportada, diagnóstico técnico, causa, solución y prioridad.",
    rf: "RF-018 a RF-021",
    singular: "diagnóstico",
    write: ["ADMIN", "MECANICO"],
    fields: [
      { name: "codigo", label: "Código" },
      { name: "placa", label: "Placa", required: true },
      { name: "mecanico", label: "Mecánico", type: "select", dynamicOptions: "mecanicos" },
      { name: "falla", label: "Falla reportada", type: "textarea", span: 2 },
      { name: "diagnostico", label: "Diagnóstico técnico", type: "textarea", span: 2 },
      { name: "causa", label: "Causa", type: "textarea", span: 2 },
      { name: "solucion", label: "Solución propuesta", type: "textarea", span: 2 },
      { name: "prioridad", label: "Prioridad", type: "select", options: ["Baja", "Media", "Alta", "Crítica"] },
      { name: "aprobacion", label: "Aprobación", type: "select", options: ["Pendiente", "Aprobada", "Rechazada", "Parcialmente aprobada"] },
    ],
    columns: [
      { name: "codigo", label: "Código" },
      { name: "placa", label: "Placa" },
      { name: "falla", label: "Falla reportada" },
      { name: "mecanico", label: "Mecánico" },
      { name: "prioridad", label: "Prioridad", kind: "badge" },
      { name: "aprobacion", label: "Aprobación", kind: "badge" },
    ],
    seed: [
      {
        id: "d1",
        codigo: "DX-0921",
        placa: "KIA412",
        mecanico: "Andrés Molina",
        falla: "Golpeteo al pasar reductores",
        diagnostico: "Amortiguadores delanteros con fuga de aceite y bujes desgastados.",
        causa: "Desgaste natural por kilometraje.",
        solucion: "Reemplazo de par de amortiguadores y kit de bujes.",
        prioridad: "Alta",
        aprobacion: "Aprobada",
      },
      {
        id: "d2",
        codigo: "DX-0922",
        placa: "TWQ889",
        mecanico: "Julián Ospina",
        falla: "Pedal de freno esponjoso",
        diagnostico: "Aire en el circuito hidráulico y pastillas al límite.",
        causa: "Mantenimiento vencido.",
        solucion: "Purga de sistema y cambio de pastillas delanteras.",
        prioridad: "Crítica",
        aprobacion: "Pendiente",
      },
    ],
  },

  cotizaciones: {
    key: "cotizaciones",
    title: "Cotizaciones",
    subtitle: "Versiones, vigencia, aprobación parcial y conversión a orden de trabajo.",
    rf: "RF-055 a RF-059",
    singular: "cotización",
    write: ["ADMIN"],
    fields: [
      { name: "numero", label: "Número" },
      { name: "version", label: "Versión", type: "number" },
      { name: "cliente", label: "Cliente", required: true },
      { name: "placa", label: "Placa" },
      { name: "diagnostico", label: "Diagnóstico asociado" },
      { name: "fecha", label: "Fecha creación", type: "date" },
      { name: "vencimiento", label: "Fecha vencimiento", type: "date" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "iva", label: "IVA", type: "number" },
      { name: "descuento", label: "Descuento", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: ["Vigente", "Vencida", "Aprobada", "Rechazada", "Parcialmente aprobada"] },
    ],
    columns: [
      { name: "numero", label: "Número" },
      { name: "version", label: "Ver." },
      { name: "cliente", label: "Cliente" },
      { name: "placa", label: "Placa" },
      { name: "vencimiento", label: "Vence" },
      { name: "total", label: "Total", kind: "money" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "q1",
        numero: "COT-2026-0331",
        version: 2,
        cliente: "María Fernanda Gómez",
        placa: "KIA412",
        diagnostico: "DX-0921",
        fecha: "2026-08-06",
        vencimiento: "2026-08-20",
        subtotal: 1420000,
        iva: 269800,
        descuento: 50000,
        total: 1639800,
        estado: "Aprobada",
      },
      {
        id: "q2",
        numero: "COT-2026-0332",
        version: 1,
        cliente: "Transportes Andinos S.A.S.",
        placa: "TWQ889",
        diagnostico: "DX-0922",
        fecha: "2026-08-05",
        vencimiento: "2026-08-12",
        subtotal: 890000,
        iva: 169100,
        descuento: 0,
        total: 1059100,
        estado: "Vigente",
      },
    ],
  },

  ordenes: {
    key: "ordenes",
    title: "Órdenes de trabajo",
    subtitle: "Ciclo completo de la orden, asignación de mecánicos y bitácora de estados.",
    rf: "RF-022 a RF-025",
    singular: "orden",
    write: ["ADMIN"],
    fields: [
      { name: "numero", label: "Número" },
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "cliente", label: "Cliente", required: true },
      { name: "placa", label: "Placa", required: true },
      { name: "mecanico", label: "Mecánico asignado", type: "select", dynamicOptions: "mecanicos" },
      { name: "responsable", label: "Responsable" },
      {
        name: "estado",
        label: "Estado",
        type: "select",
        options: [
          "Pendiente",
          "Diagnóstico",
          "Esperando aprobación",
          "Esperando repuestos",
          "En reparación",
          "En pruebas",
          "Lista para entrega",
          "Entregada",
          "Cancelada",
        ],
      },
      { name: "total", label: "Total", type: "number" },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "numero", label: "Orden" },
      { name: "fecha", label: "Fecha" },
      { name: "cliente", label: "Cliente" },
      { name: "placa", label: "Placa" },
      { name: "mecanico", label: "Mecánico" },
      { name: "estado", label: "Estado", kind: "badge" },
      { name: "total", label: "Total", kind: "money" },
    ],
    seed: [
      {
        id: "o1",
        numero: "OT-2026-0512",
        fecha: "2026-08-06",
        cliente: "María Fernanda Gómez",
        placa: "KIA412",
        mecanico: "Andrés Molina",
        responsable: "Carlos Restrepo",
        estado: "En reparación",
        total: 1639800,
        observaciones: "Cliente aprobó cotización versión 2.",
      },
      {
        id: "o2",
        numero: "OT-2026-0511",
        fecha: "2026-08-05",
        cliente: "Transportes Andinos S.A.S.",
        placa: "TWQ889",
        mecanico: "Julián Ospina",
        responsable: "Carlos Restrepo",
        estado: "Esperando aprobación",
        total: 1059100,
        observaciones: "",
      },
      {
        id: "o3",
        numero: "OT-2026-0509",
        fecha: "2026-08-03",
        cliente: "Jorge Iván Cardona",
        placa: "HRT205",
        mecanico: "Andrés Molina",
        responsable: "Carlos Restrepo",
        estado: "Lista para entrega",
        total: 480000,
        observaciones: "Pendiente facturación.",
      },
    ],
  },

  mantenimiento: {
    key: "mantenimiento",
    title: "Mantenimiento",
    subtitle: "Actividades ejecutadas, tiempos, horas hombre y observaciones técnicas.",
    rf: "RF-026 a RF-029",
    singular: "actividad",
    write: ["ADMIN", "MECANICO"],
    fields: [
      { name: "orden", label: "Orden", type: "combo", dynamicOptions: "ordenes", required: true },
      { name: "actividad", label: "Actividad", required: true },
      { name: "mecanico", label: "Mecánico", type: "select", dynamicOptions: "mecanicos" },
      { name: "horaInicio", label: "Hora inicio" },
      { name: "horaFin", label: "Hora fin" },
      { name: "horasHombre", label: "Horas hombre", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: ["En proceso", "Finalizada"] },
      { name: "observaciones", label: "Observaciones técnicas", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "orden", label: "Orden" },
      { name: "actividad", label: "Actividad" },
      { name: "mecanico", label: "Mecánico" },
      { name: "horaInicio", label: "Inicio" },
      { name: "horaFin", label: "Fin" },
      { name: "horasHombre", label: "H/H", kind: "number" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      {
        id: "m1",
        orden: "OT-2026-0512",
        actividad: "Cambio de amortiguadores",
        mecanico: "Andrés Molina",
        horaInicio: "09:00",
        horaFin: "11:30",
        horasHombre: 2.5,
        estado: "Finalizada",
        observaciones: "Se recomienda alineación posterior.",
      },
      {
        id: "m2",
        orden: "OT-2026-0512",
        actividad: "Alineación y balanceo",
        mecanico: "Andrés Molina",
        horaInicio: "11:40",
        horaFin: "",
        horasHombre: 0,
        estado: "En proceso",
        observaciones: "",
      },
    ],
  },

  servicios: {
    key: "servicios",
    title: "Catálogo de servicios",
    subtitle: "Códigos, categorías, tiempo estimado y precio sugerido.",
    rf: "RF-030 a RF-032",
    singular: "servicio",
    write: ["ADMIN"],
    fields: [
      { name: "codigo", label: "Código", required: true },
      { name: "nombre", label: "Nombre", required: true },
      { name: "categoria", label: "Categoría", type: "select", options: ["Motor", "Frenos", "Suspensión", "Electricidad", "Preventivo", "Diagnóstico"] },
      { name: "tiempoEstimado", label: "Tiempo estimado (h)", type: "number" },
      { name: "precio", label: "Precio sugerido", type: "number" },
      { name: "garantiaDias", label: "Garantía (días)", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: ESTADOS },
    ],
    columns: [
      { name: "codigo", label: "Código" },
      { name: "nombre", label: "Servicio" },
      { name: "categoria", label: "Categoría", kind: "badge" },
      { name: "tiempoEstimado", label: "Horas", kind: "number" },
      { name: "precio", label: "Precio", kind: "money" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "s1", codigo: "SRV-001", nombre: "Cambio de aceite y filtro", categoria: "Preventivo", tiempoEstimado: 0.8, precio: 95000, garantiaDias: 90, estado: "Activo" },
      { id: "s2", codigo: "SRV-014", nombre: "Cambio de pastillas de freno", categoria: "Frenos", tiempoEstimado: 1.5, precio: 160000, garantiaDias: 180, estado: "Activo" },
      { id: "s3", codigo: "SRV-022", nombre: "Escaneo electrónico completo", categoria: "Diagnóstico", tiempoEstimado: 1, precio: 80000, garantiaDias: 0, estado: "Activo" },
      { id: "s4", codigo: "SRV-031", nombre: "Cambio de amortiguadores", categoria: "Suspensión", tiempoEstimado: 3, precio: 320000, garantiaDias: 180, estado: "Activo" },
    ],
  },

  proveedores: {
    key: "proveedores",
    title: "Proveedores",
    subtitle: "Proveedores de repuestos e insumos. NIT único, sin borrado físico.",
    rf: "RF-033 a RF-035",
    singular: "proveedor",
    write: ["ADMIN"],
    fields: [
      { name: "nit", label: "NIT / documento", required: true },
      { name: "razonSocial", label: "Razón social", required: true },
      { name: "nombreComercial", label: "Nombre comercial" },
      { name: "contacto", label: "Persona de contacto" },
      { name: "telefono", label: "Teléfono" },
      { name: "correo", label: "Correo" },
      { name: "direccion", label: "Dirección" },
      { name: "ciudad", label: "Ciudad" },
      { name: "estado", label: "Estado", type: "select", options: ESTADOS },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "nit", label: "NIT" },
      { name: "razonSocial", label: "Razón social" },
      { name: "contacto", label: "Contacto" },
      { name: "telefono", label: "Teléfono" },
      { name: "ciudad", label: "Ciudad" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "p1", nit: "890900608-9", razonSocial: "Distribuidora Autopartes del Valle S.A.S.", nombreComercial: "Autopartes Valle", contacto: "Luz Marina Peña", telefono: "6023344551", correo: "ventas@apvalle.co", direccion: "Cll 70 #22-11", ciudad: "Cali", estado: "Activo", observaciones: "" },
      { id: "p2", nit: "811022114-2", razonSocial: "Lubricantes y Filtros Andinos Ltda.", nombreComercial: "Lufan", contacto: "Diego Sánchez", telefono: "6044412200", correo: "pedidos@lufan.co", direccion: "Cra 50 #30-08", ciudad: "Medellín", estado: "Activo", observaciones: "Entrega en 24 horas." },
      { id: "p3", nit: "830112009-4", razonSocial: "Frenos Técnicos Nacionales S.A.", nombreComercial: "Fretec", contacto: "Paula Ríos", telefono: "6017788990", correo: "info@fretec.co", direccion: "Zona Industrial Bod 12", ciudad: "Bogotá", estado: "Inactivo", observaciones: "" },
    ],
  },

  inventario: {
    key: "inventario",
    title: "Inventario de repuestos",
    subtitle: "Stock, precios, ubicación, garantía y alertas de mínimos.",
    rf: "RF-036 a RF-043",
    singular: "repuesto",
    write: ["ADMIN"],
    fields: [
      { name: "codigo", label: "Código interno", required: true },
      { name: "codigoBarras", label: "Código de barras" },
      { name: "nombre", label: "Nombre", required: true },
      { name: "marca", label: "Marca" },
      { name: "referencia", label: "Referencia" },
      { name: "categoria", label: "Categoría", type: "select", options: ["Aceites", "Filtros", "Frenos", "Suspensión", "Dirección", "Motor", "Caja de cambios", "Embrague", "Refrigeración", "Eléctrico", "Llantas", "Baterías", "Sensores", "Lubricantes", "Accesorios", "Otros"] },
      { name: "unidad", label: "Unidad de medida", type: "select", options: ["Unidad", "Litro", "Galón", "Juego", "Metro"] },
      { name: "stock", label: "Stock actual", type: "number" },
      { name: "stockMin", label: "Stock mínimo", type: "number" },
      { name: "stockMax", label: "Stock máximo", type: "number" },
      { name: "ubicacion", label: "Ubicación física" },
      { name: "precioCompra", label: "Precio de compra", type: "number" },
      { name: "precioVenta", label: "Precio de venta", type: "number" },
      { name: "iva", label: "IVA (%)", type: "number" },
      { name: "proveedor", label: "Proveedor principal" },
      { name: "garantiaDias", label: "Garantía (días)", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: [...ESTADOS, "Descontinuado"] },
      { name: "descripcion", label: "Descripción", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "codigo", label: "Código" },
      { name: "nombre", label: "Repuesto" },
      { name: "categoria", label: "Categoría", kind: "badge" },
      { name: "stock", label: "Stock", kind: "number" },
      { name: "stockMin", label: "Mín.", kind: "number" },
      { name: "precioVenta", label: "P. venta", kind: "money" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "i1", codigo: "RP-1001", codigoBarras: "7701234500019", nombre: "Aceite sintético 5W-30", marca: "Mobil", referencia: "M15W30-4L", categoria: "Aceites", unidad: "Galón", stock: 24, stockMin: 8, stockMax: 60, ubicacion: "A-01-3", precioCompra: 118000, precioVenta: 165000, iva: 19, proveedor: "Lufan", garantiaDias: 0, estado: "Activo", descripcion: "" },
      { id: "i2", codigo: "RP-1042", codigoBarras: "7701234500422", nombre: "Filtro de aceite", marca: "Mann", referencia: "W71280", categoria: "Filtros", unidad: "Unidad", stock: 6, stockMin: 10, stockMax: 40, ubicacion: "B-02-1", precioCompra: 24000, precioVenta: 39000, iva: 19, proveedor: "Lufan", garantiaDias: 90, estado: "Activo", descripcion: "" },
      { id: "i3", codigo: "RP-2210", codigoBarras: "7701234522104", nombre: "Pastillas de freno delanteras", marca: "Fretec", referencia: "FT-D2210", categoria: "Frenos", unidad: "Juego", stock: 0, stockMin: 4, stockMax: 20, ubicacion: "C-01-2", precioCompra: 96000, precioVenta: 158000, iva: 19, proveedor: "Fretec", garantiaDias: 180, estado: "Activo", descripcion: "Agotado, pedido en tránsito." },
      { id: "i4", codigo: "RP-3301", codigoBarras: "7701234533015", nombre: "Amortiguador delantero", marca: "Monroe", referencia: "MN-3301", categoria: "Suspensión", unidad: "Unidad", stock: 5, stockMin: 2, stockMax: 12, ubicacion: "D-03-4", precioCompra: 210000, precioVenta: 315000, iva: 19, proveedor: "Autopartes Valle", garantiaDias: 365, estado: "Activo", descripcion: "" },
      { id: "i5", codigo: "RP-4400", codigoBarras: "7701234544009", nombre: "Batería 12V 60Ah", marca: "Willard", referencia: "W-60D", categoria: "Baterías", unidad: "Unidad", stock: 3, stockMin: 3, stockMax: 10, ubicacion: "E-01-1", precioCompra: 320000, precioVenta: 465000, iva: 19, proveedor: "Autopartes Valle", garantiaDias: 365, estado: "Activo", descripcion: "" },
    ],
  },

  movimientos: {
    key: "movimientos",
    title: "Kardex y movimientos",
    subtitle: "Trazabilidad inalterable de entradas, salidas, ajustes y devoluciones.",
    rf: "RF-040 · RF-041 · RF-051",
    singular: "movimiento",
    write: ["ADMIN"],
    fields: [
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "hora", label: "Hora" },
      { name: "repuesto", label: "Repuesto", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: ["Entrada", "Salida", "Ajuste", "Devolución", "Traslado"] },
      { name: "cantidad", label: "Cantidad", type: "number" },
      { name: "saldo", label: "Saldo", type: "number" },
      { name: "documento", label: "Documento asociado" },
      { name: "usuario", label: "Usuario" },
      { name: "observacion", label: "Observación", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "fecha", label: "Fecha" },
      { name: "repuesto", label: "Repuesto" },
      { name: "tipo", label: "Tipo", kind: "badge" },
      { name: "cantidad", label: "Cant.", kind: "number" },
      { name: "saldo", label: "Saldo", kind: "number" },
      { name: "documento", label: "Documento" },
      { name: "usuario", label: "Usuario" },
    ],
    seed: [
      { id: "k1", fecha: "2026-08-06", hora: "10:12", repuesto: "RP-3301 Amortiguador delantero", tipo: "Salida", cantidad: 2, saldo: 5, documento: "OT-2026-0512", usuario: "amolina", observacion: "Consumo en orden de trabajo." },
      { id: "k2", fecha: "2026-08-05", hora: "16:40", repuesto: "RP-1042 Filtro de aceite", tipo: "Entrada", cantidad: 12, saldo: 6, documento: "COM-2026-0088", usuario: "crestrepo", observacion: "Compra a Lufan." },
      { id: "k3", fecha: "2026-08-04", hora: "09:05", repuesto: "RP-2210 Pastillas de freno delanteras", tipo: "Salida", cantidad: 4, saldo: 0, documento: "OT-2026-0509", usuario: "jospina", observacion: "" },
      { id: "k4", fecha: "2026-08-03", hora: "11:20", repuesto: "RP-1001 Aceite sintético 5W-30", tipo: "Ajuste", cantidad: -1, saldo: 24, documento: "AJU-0031", usuario: "crestrepo", observacion: "Diferencia en conteo físico." },
    ],
  },

  compras: {
    key: "compras",
    title: "Compras",
    subtitle: "Compras a proveedores con actualización automática de inventario y kardex.",
    rf: "RF-044 a RF-047",
    singular: "compra",
    write: ["ADMIN"],
    fields: [
      { name: "numero", label: "Número" },
      { name: "proveedor", label: "Proveedor", required: true },
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "factura", label: "Número de factura" },
      { name: "formaPago", label: "Forma de pago", type: "select", options: ["Contado", "Crédito 15 días", "Crédito 30 días", "Transferencia"] },
      { name: "items", label: "Ítems", type: "number" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "iva", label: "IVA", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: ["Borrador", "Confirmada", "Anulada"] },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "numero", label: "Compra" },
      { name: "fecha", label: "Fecha" },
      { name: "proveedor", label: "Proveedor" },
      { name: "factura", label: "Factura" },
      { name: "items", label: "Ítems", kind: "number" },
      { name: "total", label: "Total", kind: "money" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "cp1", numero: "COM-2026-0088", proveedor: "Lufan", fecha: "2026-08-05", factura: "FV-88214", formaPago: "Crédito 30 días", items: 3, subtotal: 1240000, iva: 235600, total: 1475600, estado: "Confirmada", observaciones: "" },
      { id: "cp2", numero: "COM-2026-0089", proveedor: "Fretec", fecha: "2026-08-06", factura: "FE-2211", formaPago: "Contado", items: 1, subtotal: 384000, iva: 72960, total: 456960, estado: "Borrador", observaciones: "Pendiente confirmar recepción física." },
    ],
  },

  repuestosOrden: {
    key: "repuestosOrden",
    title: "Repuestos utilizados",
    subtitle: "Consumo de repuestos por orden con validación de existencias y garantía.",
    rf: "RF-048 a RF-052",
    singular: "consumo",
    write: ["ADMIN", "MECANICO"],
    fields: [
      { name: "orden", label: "Orden", type: "combo", dynamicOptions: "ordenes", required: true },
      { name: "repuesto", label: "Repuesto", required: true },
      { name: "cantidad", label: "Cantidad", type: "number" },
      { name: "precioUnitario", label: "Precio unitario", type: "number" },
      { name: "iva", label: "IVA (%)", type: "number" },
      { name: "descuento", label: "Descuento", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "instalacion", label: "Fecha instalación", type: "date" },
      { name: "vencimientoGarantia", label: "Vence garantía", type: "date" },
      { name: "lote", label: "Lote" },
      { name: "serie", label: "Serie" },
      { name: "estado", label: "Estado", type: "select", options: ["Instalado", "Devuelto"] },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "orden", label: "Orden" },
      { name: "repuesto", label: "Repuesto" },
      { name: "cantidad", label: "Cant.", kind: "number" },
      { name: "precioUnitario", label: "Unitario", kind: "money" },
      { name: "total", label: "Total", kind: "money" },
      { name: "vencimientoGarantia", label: "Garantía hasta" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "ru1", orden: "OT-2026-0512", repuesto: "RP-3301 Amortiguador delantero", cantidad: 2, precioUnitario: 315000, iva: 19, descuento: 0, total: 749700, instalacion: "2026-08-06", vencimientoGarantia: "2027-08-06", lote: "L-2299", serie: "", estado: "Instalado", observaciones: "" },
      { id: "ru2", orden: "OT-2026-0509", repuesto: "RP-2210 Pastillas de freno delanteras", cantidad: 1, precioUnitario: 158000, iva: 19, descuento: 10000, total: 176120, instalacion: "2026-08-03", vencimientoGarantia: "2027-02-03", lote: "L-8871", serie: "", estado: "Instalado", observaciones: "" },
    ],
  },

  manoObra: {
    key: "manoObra",
    title: "Mano de obra",
    subtitle: "Horas trabajadas, valor hora y costo real por actividad y mecánico.",
    rf: "RF-053 · RF-054",
    singular: "registro",
    write: ["ADMIN", "MECANICO"],
    fields: [
      { name: "orden", label: "Orden", type: "combo", dynamicOptions: "ordenes", required: true },
      { name: "actividad", label: "Actividad" },
      {
        name: "mecanico",
        label: "Mecánico responsable",
        type: "select",
        dynamicOptions: "mecanicos",
        required: true,
      },
      { name: "horas", label: "Horas trabajadas", type: "number" },
      { name: "valorHora", label: "Valor por hora", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "orden", label: "Orden" },
      { name: "actividad", label: "Actividad" },
      { name: "mecanico", label: "Mecánico" },
      { name: "horas", label: "Horas", kind: "number" },
      { name: "valorHora", label: "Valor hora", kind: "money" },
      { name: "total", label: "Total", kind: "money" },
    ],
    seed: [
      { id: "mo1", orden: "OT-2026-0512", actividad: "Cambio de amortiguadores", mecanico: "Andrés Molina", horas: 2.5, valorHora: 45000, total: 112500, observaciones: "" },
      { id: "mo2", orden: "OT-2026-0509", actividad: "Cambio de pastillas", mecanico: "Julián Ospina", horas: 1.5, valorHora: 45000, total: 67500, observaciones: "" },
    ],
  },

  facturas: {
    key: "facturas",
    title: "Facturación",
    subtitle: "Facturas consecutivas generadas desde órdenes finalizadas, con pagos mixtos.",
    rf: "RF-060 a RF-063",
    singular: "factura",
    write: ["ADMIN"],
    fields: [
      { name: "numero", label: "Número de factura" },
      { name: "fecha", label: "Fecha de emisión", type: "date" },
      { name: "orden", label: "Orden de trabajo", type: "combo", dynamicOptions: "ordenes", required: true },
      { name: "cliente", label: "Cliente", required: true },
      { name: "documento", label: "Documento" },
      { name: "placa", label: "Placa" },
      { name: "kilometraje", label: "Kilometraje", type: "number" },
      { name: "mecanico", label: "Mecánico responsable", type: "select", dynamicOptions: "mecanicos" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "iva", label: "IVA", type: "number" },
      { name: "descuento", label: "Descuentos", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "metodoPago", label: "Método de pago", type: "select", options: ["Efectivo", "Tarjeta débito", "Tarjeta crédito", "Transferencia", "Nequi", "Daviplata", "Crédito", "Mixto", "Otro"] },
      { name: "estado", label: "Estado", type: "select", options: ["Pendiente", "Pagada", "Parcialmente pagada", "Anulada"] },
      { name: "observaciones", label: "Observaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "numero", label: "Factura" },
      { name: "fecha", label: "Fecha" },
      { name: "cliente", label: "Cliente" },
      { name: "placa", label: "Placa" },
      { name: "total", label: "Total", kind: "money" },
      { name: "metodoPago", label: "Pago" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "f1", numero: "FAC-2026-0301", fecha: "2026-08-03", orden: "OT-2026-0509", cliente: "Jorge Iván Cardona", documento: "71554332", placa: "HRT205", kilometraje: 96700, mecanico: "Andrés Molina", subtotal: 403361, iva: 76639, descuento: 0, total: 480000, metodoPago: "Efectivo", estado: "Pagada", observaciones: "" },
      { id: "f2", numero: "FAC-2026-0302", fecha: "2026-08-05", orden: "OT-2026-0505", cliente: "Transportes Andinos S.A.S.", documento: "900455112-3", placa: "TWQ889", kilometraje: 213900, mecanico: "Julián Ospina", subtotal: 890000, iva: 169100, descuento: 0, total: 1059100, metodoPago: "Crédito", estado: "Parcialmente pagada", observaciones: "Abono del 50%." },
    ],
  },

  entregas: {
    key: "entregas",
    title: "Entrega de vehículos",
    subtitle: "Validación de orden, factura y pago antes de la entrega. Genera acta.",
    rf: "RF-064 · RF-065",
    singular: "entrega",
    write: ["ADMIN"],
    fields: [
      { name: "acta", label: "Acta" },
      { name: "orden", label: "Orden", type: "combo", dynamicOptions: "ordenes", required: true },
      { name: "placa", label: "Placa" },
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "hora", label: "Hora" },
      { name: "recibe", label: "Persona que recibe", required: true },
      { name: "documento", label: "Documento" },
      { name: "proximoMantenimiento", label: "Próximo mantenimiento" },
      { name: "estado", label: "Estado", type: "select", options: ["Entregado", "Pendiente"] },
      { name: "observaciones", label: "Recomendaciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "acta", label: "Acta" },
      { name: "orden", label: "Orden" },
      { name: "placa", label: "Placa" },
      { name: "fecha", label: "Fecha" },
      { name: "recibe", label: "Recibe" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "e1", acta: "ACT-2026-0210", orden: "OT-2026-0509", placa: "HRT205", fecha: "2026-08-03", hora: "17:20", recibe: "Jorge Iván Cardona", documento: "71554332", proximoMantenimiento: "101.700 km o 6 meses", estado: "Entregado", observaciones: "Revisar alineación en 1.000 km." },
    ],
  },

  garantias: {
    key: "garantias",
    title: "Garantías",
    subtitle: "Garantías de servicios y repuestos instalados, con fechas de vencimiento.",
    rf: "RF-069 a RF-071",
    singular: "garantía",
    write: ["ADMIN"],
    fields: [
      { name: "tipo", label: "Tipo", type: "select", options: ["Servicio", "Repuesto"] },
      { name: "descripcion", label: "Descripción", required: true },
      { name: "cliente", label: "Cliente" },
      { name: "placa", label: "Placa" },
      { name: "orden", label: "Orden", type: "combo", dynamicOptions: "ordenes" },
      { name: "inicio", label: "Fecha instalación", type: "date" },
      { name: "vence", label: "Fecha vencimiento", type: "date" },
      { name: "estado", label: "Estado", type: "select", options: ["Vigente", "Por vencer", "Vencida", "Reclamada"] },
      { name: "condiciones", label: "Condiciones", type: "textarea", span: 2 },
    ],
    columns: [
      { name: "tipo", label: "Tipo", kind: "badge" },
      { name: "descripcion", label: "Descripción" },
      { name: "placa", label: "Placa" },
      { name: "orden", label: "Orden" },
      { name: "vence", label: "Vence" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "g1", tipo: "Repuesto", descripcion: "Amortiguador delantero Monroe MN-3301", cliente: "María Fernanda Gómez", placa: "KIA412", orden: "OT-2026-0512", inicio: "2026-08-06", vence: "2027-08-06", estado: "Vigente", condiciones: "No cubre daño por impacto." },
      { id: "g2", tipo: "Servicio", descripcion: "Cambio de pastillas de freno", cliente: "Jorge Iván Cardona", placa: "HRT205", orden: "OT-2026-0509", inicio: "2026-08-03", vence: "2026-08-31", estado: "Por vencer", condiciones: "Sujeta a uso normal." },
    ],
  },

  notificaciones: {
    key: "notificaciones",
    title: "Centro de notificaciones",
    subtitle: "Alertas de stock, órdenes atrasadas, garantías y cotizaciones vencidas.",
    rf: "RF-086 · RF-087",
    singular: "notificación",
    write: ["ADMIN"],
    fields: [
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "tipo", label: "Tipo", type: "select", options: ["Stock mínimo", "Orden atrasada", "Garantía por vencer", "Cotización vencida", "Mantenimiento preventivo"] },
      { name: "mensaje", label: "Mensaje", required: true, span: 2 },
      { name: "prioridad", label: "Prioridad", type: "select", options: ["Baja", "Media", "Alta", "Crítica"] },
      { name: "estado", label: "Estado", type: "select", options: ["No leída", "Leída"] },
    ],
    columns: [
      { name: "fecha", label: "Fecha" },
      { name: "tipo", label: "Tipo", kind: "badge" },
      { name: "mensaje", label: "Mensaje" },
      { name: "prioridad", label: "Prioridad", kind: "badge" },
      { name: "estado", label: "Estado", kind: "badge" },
    ],
    seed: [
      { id: "n1", fecha: "2026-08-06", tipo: "Stock mínimo", mensaje: "RP-1042 Filtro de aceite por debajo del mínimo (6 de 10).", prioridad: "Alta", estado: "No leída" },
      { id: "n2", fecha: "2026-08-06", tipo: "Stock mínimo", mensaje: "RP-2210 Pastillas de freno delanteras agotado.", prioridad: "Crítica", estado: "No leída" },
      { id: "n3", fecha: "2026-08-06", tipo: "Garantía por vencer", mensaje: "Garantía de servicio de HRT205 vence en 25 días.", prioridad: "Media", estado: "Leída" },
      { id: "n4", fecha: "2026-08-05", tipo: "Cotización vencida", mensaje: "COT-2026-0329 superó su fecha de vigencia.", prioridad: "Baja", estado: "Leída" },
    ],
  },

  auditoria: {
    key: "auditoria",
    title: "Auditoría",
    subtitle: "Bitácora inalterable de acciones e historial de cambios valor anterior / nuevo.",
    rf: "RF-083 a RF-085",
    singular: "registro",
    write: [],
    fields: [
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "hora", label: "Hora" },
      { name: "usuario", label: "Usuario" },
      { name: "modulo", label: "Módulo" },
      { name: "accion", label: "Acción" },
      { name: "valorAnterior", label: "Valor anterior" },
      { name: "valorNuevo", label: "Valor nuevo" },
      { name: "ip", label: "Dirección IP" },
    ],
    columns: [
      { name: "fecha", label: "Fecha" },
      { name: "hora", label: "Hora" },
      { name: "usuario", label: "Usuario" },
      { name: "modulo", label: "Módulo", kind: "badge" },
      { name: "accion", label: "Acción" },
      { name: "valorAnterior", label: "Anterior" },
      { name: "valorNuevo", label: "Nuevo" },
      { name: "ip", label: "IP" },
    ],
    seed: [
      { id: "a1", fecha: "2026-08-06", hora: "10:12", usuario: "amolina", modulo: "Órdenes", accion: "Cambio de estado", valorAnterior: "Esperando repuestos", valorNuevo: "En reparación", ip: "192.168.1.42" },
      { id: "a2", fecha: "2026-08-06", hora: "09:58", usuario: "crestrepo", modulo: "Inventario", accion: "Actualización de precio", valorAnterior: "155000", valorNuevo: "165000", ip: "192.168.1.10" },
      { id: "a3", fecha: "2026-08-05", hora: "16:41", usuario: "crestrepo", modulo: "Compras", accion: "Confirmación de compra", valorAnterior: "Borrador", valorNuevo: "Confirmada", ip: "192.168.1.10" },
      { id: "a4", fecha: "2026-08-05", hora: "08:02", usuario: "jospina", modulo: "Autenticación", accion: "Bloqueo por 5 intentos fallidos", valorAnterior: "Activo", valorNuevo: "Bloqueado", ip: "192.168.1.77" },
    ],
  },
};

export const CHECKLIST_ITEMS = [
  "Luces",
  "Llantas",
  "Rines",
  "Espejos",
  "Radio",
  "Vidrios",
  "Limpiabrisas",
  "Aire acondicionado",
  "Herramientas",
  "Llanta de repuesto",
  "Botiquín",
  "Extintor",
  "Triángulos",
  "Gato",
];

export const CHECKLIST_ESTADOS = ["Bueno", "Regular", "Malo", "No aplica"];

export const FOTO_CATEGORIAS = [
  "Frontal",
  "Trasera",
  "Lateral izquierdo",
  "Lateral derecho",
  "Interior",
  "Motor",
  "Otros daños",
];

export const ACTIVIDADES_CATALOGO = [
  "Cambio aceite",
  "Cambio filtros",
  "Cambio batería",
  "Cambio amortiguadores",
  "Cambio suspensión",
  "Cambio frenos",
  "Cambio embrague",
  "Cambio correa",
  "Cambio bomba agua",
  "Reparación caja",
  "Reparación motor",
  "Afinación",
  "Balanceo",
  "Alineación",
  "Escaneo electrónico",
];
